- name: Install Monitoring Service for VDI
  hosts: all

  tasks:
    - name: Deleting the file if exist
      win_file:
        path: 'C:\\Users\Public\Documents\Setup Monitoring Services.msi'
        state: absent
#src is the path to file
    - name: Copying a file from local to remote machine
      win_copy:
        src: "Setup Services.msi"
        dest: 'C:\\Users\Public\Documents\'
#state can be present or absent if desired to install or uninstall respectively
    - name: Install MSI
      win_package:
        path: C:\\Users\Public\Documents\Setup Services.msi
        state: present
