apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
    name: tanul-role
    namespace: kong
  rules:
  - apiGroups:
    - ""
    - apps
    - configuration.konghq.com
    - rbac.authorization.k8s.io
    resources:
    - deployments
    - replicasets
    - pods
    - services
    - configmaps
    - secrets
    - kongingresses
    - kongplugins
    - serviceaccounts
    - roles
    - rolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tanul-bind
  namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tanul-role
subjects:
- kind: ServiceAccount
  name: azdev-sa-488484
  namespace: default
  
 ```
 apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: tanul-cluster-role
    namespace: kong
  rules:
  - apiGroups:
    - apiextensions.k8s.io
    - networking.k8s.io
    - rbac.authorization.k8s.io
    resources:
    - customresourcedefinitions
    - ingressclasses
    - clusterroles
    - clusterrolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
  
 ```
 
 apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanul-cluster-bind
  namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanul-cluster-role
subjects:
- kind: ServiceAccount
  name: azdev-sa-488484
  namespace: default
