apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
    name: tanul-role
    namespace: kong
  rules:
  - apiGroups:
    - ""
    - apiextensions.k8s.io
    - apps
    - configuration.konghq.com
    resources:
    - deployments
    - replicasets
    - pods
    - services
    - configmaps
    - secrets
    - customresourcedefinition
    - kongingresses
    - kongplugins
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
  
  ```
  apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tanul-bind
  namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tanul-role
subjects:
- kind: ServiceAccount
  name: azdev-sa-488484
  namespace: default
