apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"azure-devops-deploy-role","namespace":"prod"},"rules":[{"apiGroups":["","batch","extensions","apps","policy","networking.k8s.io","configuration.konghq.com"],"resources":["deployments","replicasets","pods","services","ingresses","configmaps","secrets","kongingresses","kongplugins"],"verbs":["get","list","watch","create","update","patch","delete"]}]}
    creationTimestamp: "2020-06-02T15:24:24Z"
    name: azure-devops-deploy-role
    resourceVersion: "156627311"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/prod/roles/azure-devops-deploy-role
    uid: 82ed7692-47ec-4002-9308-29307e72aa8b
  rules:
  - apiGroups:
    - ""
    - batch
    - extensions
    - apps
    - policy
    - networking.k8s.io
    - configuration.konghq.com
    resources:
    - deployments
    - replicasets
    - pods
    - services
    - ingresses
    - configmaps
    - secrets
    - kongingresses
    - kongplugins
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
